[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."line-notify"]
  node_bundler = "esbuild"

[functions."telegram-notify"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
